-- ============================================================
-- F5 HOL: Export Source Data to Stage (Run Once)
-- ============================================================
-- Run this in YOUR source account to export all RAW tables
-- as Parquet files to a named stage. Then download the files
-- to the data/ folder for distribution to attendee accounts.
-- ============================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE F5_PROD;
USE SCHEMA RAW;

-- Create export stage
CREATE OR REPLACE STAGE HOL_DATA_EXPORT
    FILE_FORMAT = (TYPE = PARQUET);

-- Export all RAW tables
COPY INTO @HOL_DATA_EXPORT/DIM_CUST_ACCT_SFDC/ FROM DIM_CUST_ACCT_SFDC FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/DIM_DAY_DATE/ FROM DIM_DAY_DATE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/DIM_GEOGRAPHIC_AREA/ FROM DIM_GEOGRAPHIC_AREA FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/DIM_PRODUCT_OFFER/ FROM DIM_PRODUCT_OFFER FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/DIM_PRODUCT_OFFER_SUBSCRIPTION/ FROM DIM_PRODUCT_OFFER_SUBSCRIPTION FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/DIM_SALES_OPPORTUNITY/ FROM DIM_SALES_OPPORTUNITY FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/DIM_SALES_USER/ FROM DIM_SALES_USER FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/DIM_SUPPORT_CASE/ FROM DIM_SUPPORT_CASE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/DIM_WORKER/ FROM DIM_WORKER FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/FACT_RMA_ORDER/ FROM FACT_RMA_ORDER FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/FACT_SALES_OPPORTUNITY/ FROM FACT_SALES_OPPORTUNITY FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/FACT_SALES_OPPORTUNITY_LINE_ITEM/ FROM FACT_SALES_OPPORTUNITY_LINE_ITEM FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/FACT_SALES_PIPELINE_SNAPSHOT/ FROM FACT_SALES_PIPELINE_SNAPSHOT FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/FACT_SUPPORT_CASE/ FROM FACT_SUPPORT_CASE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/QUOTE/ FROM QUOTE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/SALES_ACCOUNT_TEAM/ FROM SALES_ACCOUNT_TEAM FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/SALES_SECURITY_ETM_TERRITORY/ FROM SALES_SECURITY_ETM_TERRITORY FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/USER_ENTRY_HEADER/ FROM USER_ENTRY_HEADER FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD/ FROM BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE/ FROM COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/COL_INSTALL_BASE/ FROM COL_INSTALL_BASE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/COL_SALES_OPPORTUNITY_LINE_ITEM/ FROM COL_SALES_OPPORTUNITY_LINE_ITEM FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/COL_SUPPORT_CASE/ FROM COL_SUPPORT_CASE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/COL_TERM_SUB_MONTHLY_USAGE_V2/ FROM COL_TERM_SUB_MONTHLY_USAGE_V2 FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/COL_XC_PRODUCT_HEALTHSCORE/ FROM COL_XC_PRODUCT_HEALTHSCORE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/COL_XC_TELEMETRY/ FROM COL_XC_TELEMETRY FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;
COPY INTO @HOL_DATA_EXPORT/COL_XC_TELEMETRY_ACCT_MAP_V2/ FROM COL_XC_TELEMETRY_ACCT_MAP_V2 FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;

-- Export FINAL schema table (transcripts)
COPY INTO @HOL_DATA_EXPORT/ZOOM_TRANSCRIPT_SOURCE/ FROM F5_PROD.FINAL.ZOOM_TRANSCRIPT_SOURCE FILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE HEADER = TRUE;

-- ============================================================
-- After running, download files with GET:
--   GET @HOL_DATA_EXPORT file:///path/to/HOL_data_setup/data/;
--
-- Or list what was exported:
--   LIST @HOL_DATA_EXPORT;
-- ============================================================
