-- ============================================================
-- F5 HOL: Upload and Load Data (Attendee Setup - Step 2 of 3)
-- ============================================================
-- Run this via SnowSQL (PUT commands require a local client):
--   snowsql -c <connection> -f 03_load_data.sql
--
-- Prerequisites: Run 02_create_environment.sql first.
-- This script assumes data/ folder is in the same directory.
-- ============================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE F5_PROD;
USE SCHEMA RAW;

-- ============================================================
-- PUT: Upload Parquet files from local data/ folder to stage
-- ============================================================
PUT file://./data/BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD/* @HOL_DATA_STAGE/BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE/* @HOL_DATA_STAGE/COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/COL_INSTALL_BASE/* @HOL_DATA_STAGE/COL_INSTALL_BASE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/COL_SALES_OPPORTUNITY_LINE_ITEM/* @HOL_DATA_STAGE/COL_SALES_OPPORTUNITY_LINE_ITEM/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/COL_SUPPORT_CASE/* @HOL_DATA_STAGE/COL_SUPPORT_CASE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/COL_TERM_SUB_MONTHLY_USAGE_V2/* @HOL_DATA_STAGE/COL_TERM_SUB_MONTHLY_USAGE_V2/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/COL_XC_PRODUCT_HEALTHSCORE/* @HOL_DATA_STAGE/COL_XC_PRODUCT_HEALTHSCORE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/COL_XC_TELEMETRY/* @HOL_DATA_STAGE/COL_XC_TELEMETRY/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/COL_XC_TELEMETRY_ACCT_MAP_V2/* @HOL_DATA_STAGE/COL_XC_TELEMETRY_ACCT_MAP_V2/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_CUST_ACCT_SFDC/* @HOL_DATA_STAGE/DIM_CUST_ACCT_SFDC/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_DAY_DATE/* @HOL_DATA_STAGE/DIM_DAY_DATE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_GEOGRAPHIC_AREA/* @HOL_DATA_STAGE/DIM_GEOGRAPHIC_AREA/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_PRODUCT_OFFER/* @HOL_DATA_STAGE/DIM_PRODUCT_OFFER/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_PRODUCT_OFFER_SUBSCRIPTION/* @HOL_DATA_STAGE/DIM_PRODUCT_OFFER_SUBSCRIPTION/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_SALES_OPPORTUNITY/* @HOL_DATA_STAGE/DIM_SALES_OPPORTUNITY/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_SALES_USER/* @HOL_DATA_STAGE/DIM_SALES_USER/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_SUPPORT_CASE/* @HOL_DATA_STAGE/DIM_SUPPORT_CASE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/DIM_WORKER/* @HOL_DATA_STAGE/DIM_WORKER/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/FACT_RMA_ORDER/* @HOL_DATA_STAGE/FACT_RMA_ORDER/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/FACT_SALES_OPPORTUNITY/* @HOL_DATA_STAGE/FACT_SALES_OPPORTUNITY/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/FACT_SALES_OPPORTUNITY_LINE_ITEM/* @HOL_DATA_STAGE/FACT_SALES_OPPORTUNITY_LINE_ITEM/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/FACT_SALES_PIPELINE_SNAPSHOT/* @HOL_DATA_STAGE/FACT_SALES_PIPELINE_SNAPSHOT/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/FACT_SUPPORT_CASE/* @HOL_DATA_STAGE/FACT_SUPPORT_CASE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/QUOTE/* @HOL_DATA_STAGE/QUOTE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/SALES_ACCOUNT_TEAM/* @HOL_DATA_STAGE/SALES_ACCOUNT_TEAM/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/SALES_SECURITY_ETM_TERRITORY/* @HOL_DATA_STAGE/SALES_SECURITY_ETM_TERRITORY/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://./data/USER_ENTRY_HEADER/* @HOL_DATA_STAGE/USER_ENTRY_HEADER/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Upload query repository to stage
PUT file://./query_repository.sql @QUERY_REPOSITORY_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- ============================================================
-- COPY INTO: Load staged Parquet into tables
-- ============================================================
COPY INTO DIM_CUST_ACCT_SFDC FROM @HOL_DATA_STAGE/DIM_CUST_ACCT_SFDC/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_DAY_DATE FROM @HOL_DATA_STAGE/DIM_DAY_DATE/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_GEOGRAPHIC_AREA FROM @HOL_DATA_STAGE/DIM_GEOGRAPHIC_AREA/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_PRODUCT_OFFER FROM @HOL_DATA_STAGE/DIM_PRODUCT_OFFER/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_PRODUCT_OFFER_SUBSCRIPTION FROM @HOL_DATA_STAGE/DIM_PRODUCT_OFFER_SUBSCRIPTION/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_SALES_OPPORTUNITY FROM @HOL_DATA_STAGE/DIM_SALES_OPPORTUNITY/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_SALES_USER FROM @HOL_DATA_STAGE/DIM_SALES_USER/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_SUPPORT_CASE FROM @HOL_DATA_STAGE/DIM_SUPPORT_CASE/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO DIM_WORKER FROM @HOL_DATA_STAGE/DIM_WORKER/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO SALES_ACCOUNT_TEAM FROM @HOL_DATA_STAGE/SALES_ACCOUNT_TEAM/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO FACT_SALES_OPPORTUNITY FROM @HOL_DATA_STAGE/FACT_SALES_OPPORTUNITY/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO FACT_SALES_OPPORTUNITY_LINE_ITEM FROM @HOL_DATA_STAGE/FACT_SALES_OPPORTUNITY_LINE_ITEM/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO FACT_SALES_PIPELINE_SNAPSHOT FROM @HOL_DATA_STAGE/FACT_SALES_PIPELINE_SNAPSHOT/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO FACT_SUPPORT_CASE FROM @HOL_DATA_STAGE/FACT_SUPPORT_CASE/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO QUOTE FROM @HOL_DATA_STAGE/QUOTE/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO USER_ENTRY_HEADER FROM @HOL_DATA_STAGE/USER_ENTRY_HEADER/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO COL_SUPPORT_CASE FROM @HOL_DATA_STAGE/COL_SUPPORT_CASE/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO FACT_RMA_ORDER FROM @HOL_DATA_STAGE/FACT_RMA_ORDER/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO COL_INSTALL_BASE FROM @HOL_DATA_STAGE/COL_INSTALL_BASE/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE FROM @HOL_DATA_STAGE/COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO COL_XC_TELEMETRY FROM @HOL_DATA_STAGE/COL_XC_TELEMETRY/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO COL_XC_TELEMETRY_ACCT_MAP_V2 FROM @HOL_DATA_STAGE/COL_XC_TELEMETRY_ACCT_MAP_V2/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO COL_TERM_SUB_MONTHLY_USAGE_V2 FROM @HOL_DATA_STAGE/COL_TERM_SUB_MONTHLY_USAGE_V2/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO COL_XC_PRODUCT_HEALTHSCORE FROM @HOL_DATA_STAGE/COL_XC_PRODUCT_HEALTHSCORE/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD FROM @HOL_DATA_STAGE/BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO SALES_SECURITY_ETM_TERRITORY FROM @HOL_DATA_STAGE/SALES_SECURITY_ETM_TERRITORY/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
COPY INTO COL_SALES_OPPORTUNITY_LINE_ITEM FROM @HOL_DATA_STAGE/COL_SALES_OPPORTUNITY_LINE_ITEM/ FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


-- ============================================================
-- Verify row counts
-- ============================================================
SELECT 'DIM_CUST_ACCT_SFDC' AS tbl, COUNT(*) AS rows FROM DIM_CUST_ACCT_SFDC
UNION ALL SELECT 'DIM_SALES_OPPORTUNITY', COUNT(*) FROM DIM_SALES_OPPORTUNITY
UNION ALL SELECT 'DIM_SUPPORT_CASE', COUNT(*) FROM DIM_SUPPORT_CASE
UNION ALL SELECT 'COL_XC_TELEMETRY', COUNT(*) FROM COL_XC_TELEMETRY
UNION ALL SELECT 'FACT_SALES_OPPORTUNITY_LINE_ITEM', COUNT(*) FROM FACT_SALES_OPPORTUNITY_LINE_ITEM
UNION ALL SELECT 'COL_SALES_OPPORTUNITY_LINE_ITEM', COUNT(*) FROM COL_SALES_OPPORTUNITY_LINE_ITEM
ORDER BY 1;
