-- ============================================================
-- F5 HOL: Validation Script
-- ============================================================
-- Compare row counts between the source account and the newly
-- populated attendee account. Run this in the ATTENDEE account.
--
-- Expected counts are from sfsenorthamerica-demo351_aws.
-- ============================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE F5_PROD;
USE SCHEMA RAW;

SELECT
    table_name,
    actual_rows,
    expected_rows,
    CASE WHEN actual_rows = expected_rows THEN 'PASS' ELSE 'FAIL' END AS status
FROM (
    SELECT 'DIM_CUST_ACCT_SFDC' AS table_name, (SELECT COUNT(*) FROM DIM_CUST_ACCT_SFDC) AS actual_rows, 184 AS expected_rows
    UNION ALL SELECT 'DIM_DAY_DATE', (SELECT COUNT(*) FROM DIM_DAY_DATE), 1461
    UNION ALL SELECT 'DIM_GEOGRAPHIC_AREA', (SELECT COUNT(*) FROM DIM_GEOGRAPHIC_AREA), 184
    UNION ALL SELECT 'DIM_PRODUCT_OFFER', (SELECT COUNT(*) FROM DIM_PRODUCT_OFFER), 38
    UNION ALL SELECT 'DIM_PRODUCT_OFFER_SUBSCRIPTION', (SELECT COUNT(*) FROM DIM_PRODUCT_OFFER_SUBSCRIPTION), 116
    UNION ALL SELECT 'DIM_SALES_OPPORTUNITY', (SELECT COUNT(*) FROM DIM_SALES_OPPORTUNITY), 641
    UNION ALL SELECT 'DIM_SALES_USER', (SELECT COUNT(*) FROM DIM_SALES_USER), 30
    UNION ALL SELECT 'DIM_SUPPORT_CASE', (SELECT COUNT(*) FROM DIM_SUPPORT_CASE), 1125
    UNION ALL SELECT 'DIM_WORKER', (SELECT COUNT(*) FROM DIM_WORKER), 30
    UNION ALL SELECT 'SALES_ACCOUNT_TEAM', (SELECT COUNT(*) FROM SALES_ACCOUNT_TEAM), 184
    UNION ALL SELECT 'FACT_SALES_OPPORTUNITY', (SELECT COUNT(*) FROM FACT_SALES_OPPORTUNITY), 641
    UNION ALL SELECT 'FACT_SALES_OPPORTUNITY_LINE_ITEM', (SELECT COUNT(*) FROM FACT_SALES_OPPORTUNITY_LINE_ITEM), 1757
    UNION ALL SELECT 'FACT_SALES_PIPELINE_SNAPSHOT', (SELECT COUNT(*) FROM FACT_SALES_PIPELINE_SNAPSHOT), 4408
    UNION ALL SELECT 'FACT_SUPPORT_CASE', (SELECT COUNT(*) FROM FACT_SUPPORT_CASE), 1125
    UNION ALL SELECT 'QUOTE', (SELECT COUNT(*) FROM QUOTE), 560
    UNION ALL SELECT 'USER_ENTRY_HEADER', (SELECT COUNT(*) FROM USER_ENTRY_HEADER), 55
    UNION ALL SELECT 'COL_SUPPORT_CASE', (SELECT COUNT(*) FROM COL_SUPPORT_CASE), 1125
    UNION ALL SELECT 'FACT_RMA_ORDER', (SELECT COUNT(*) FROM FACT_RMA_ORDER), 74
    UNION ALL SELECT 'COL_INSTALL_BASE', (SELECT COUNT(*) FROM COL_INSTALL_BASE), 343
    UNION ALL SELECT 'COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE', (SELECT COUNT(*) FROM COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE), 343
    UNION ALL SELECT 'COL_XC_TELEMETRY', (SELECT COUNT(*) FROM COL_XC_TELEMETRY), 47450
    UNION ALL SELECT 'COL_XC_TELEMETRY_ACCT_MAP_V2', (SELECT COUNT(*) FROM COL_XC_TELEMETRY_ACCT_MAP_V2), 143
    UNION ALL SELECT 'COL_TERM_SUB_MONTHLY_USAGE_V2', (SELECT COUNT(*) FROM COL_TERM_SUB_MONTHLY_USAGE_V2), 6006
    UNION ALL SELECT 'COL_XC_PRODUCT_HEALTHSCORE', (SELECT COUNT(*) FROM COL_XC_PRODUCT_HEALTHSCORE), 116
    UNION ALL SELECT 'BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD', (SELECT COUNT(*) FROM BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD), 21535
    UNION ALL SELECT 'SALES_SECURITY_ETM_TERRITORY', (SELECT COUNT(*) FROM SALES_SECURITY_ETM_TERRITORY), 368
    UNION ALL SELECT 'COL_SALES_OPPORTUNITY_LINE_ITEM', (SELECT COUNT(*) FROM COL_SALES_OPPORTUNITY_LINE_ITEM), 1757
    UNION ALL SELECT 'ZOOM_TRANSCRIPT_SOURCE (FINAL)', (SELECT COUNT(*) FROM F5_PROD.FINAL.ZOOM_TRANSCRIPT_SOURCE), 69
)
ORDER BY status DESC, table_name;
