-- ============================================================
-- F5 Hands-On Lab: Table Definitions (Complete)
-- ============================================================
-- Full production analytics schema covering:
--   Sales, Support, Customer Success, and Telemetry
-- Run as SYSADMIN after 01_database_setup.sql
-- ============================================================

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE F5_PROD;
USE SCHEMA RAW;

-- ============================================================
-- DIMENSION: ACCOUNTS (Salesforce CRM)
-- ============================================================
CREATE OR REPLACE TABLE DIM_CUST_ACCT_SFDC (
    DIM_CUST_ACCT_SFDC_KEY VARCHAR(32),
    SFDCF5_ACCT_ID VARCHAR(18) PRIMARY KEY,
    ACCT_NAME VARCHAR(765),
    ACCT_TYPE_CODE VARCHAR(765),
    ACCT_STATUS_CODE VARCHAR(765),
    ACCT_OWNER_NAME VARCHAR(363),
    ACCT_OWNER_ID VARCHAR(18),
    PARENT_ACCT_ID VARCHAR(18),
    INDUSTRY_NAME VARCHAR(765),
    INDUSTRY_GROUPING_CODE VARCHAR(765),
    ANNUAL_REVENUE_AMT NUMBER(38,5),
    EMPLOYEE_CNT NUMBER(38,0),
    EMPLOYEE_BUCKET_CODE VARCHAR(18),
    BILLING_CITY_NAME VARCHAR(120),
    BILLING_STATE_PROVINCE_NAME VARCHAR(240),
    BILLING_COUNTRY_NAME VARCHAR(240),
    BILLING_ZIP_POSTAL_CODE VARCHAR(60),
    THEATER_NAME VARCHAR(765),
    THEATER_CODE VARCHAR(3900),
    ETM_TERRITORY_CODE VARCHAR(765),
    ETM_TERRITORY_NAME VARCHAR(300),
    ETM_REGION_NAME VARCHAR(300),
    VARICENT_TERRITORY_CODE VARCHAR(765),
    FORTUNE_1000_RANK_NUM NUMBER(38,5),
    WEBSITE_URL_TEXT VARCHAR(16777216),
    TICKER_SYMBOL_CODE VARCHAR(60),
    LAST_ACTIVITY_DATE DATE,
    LAST_PRODUCT_CLOSE_DATETIME TIMESTAMP_NTZ(9),
    LAST_RENEWAL_CLOSE_DATETIME TIMESTAMP_NTZ(9),
    FIRST_CLOSE_DATE DATE,
    CSM_ID VARCHAR(18),
    CREATED_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- DIMENSION: GEOGRAPHIC AREAS / TERRITORIES
-- ============================================================
CREATE OR REPLACE TABLE DIM_GEOGRAPHIC_AREA (
    DIM_GEOGRAPHIC_AREA_KEY VARCHAR(32),
    GEOGRAPHIC_AREA_ID VARCHAR(18) PRIMARY KEY,
    GEOGRAPHIC_AREA_CODE VARCHAR(60),
    GEOGRAPHIC_AREA_TYPE_CODE VARCHAR(765),
    TERRITORY_ID VARCHAR(18),
    TERRITORY_NAME VARCHAR(240),
    DISTRICT_ID VARCHAR(18),
    DISTRICT_NAME VARCHAR(90),
    REGION_ID VARCHAR(18),
    REGION_NAME VARCHAR(765),
    SUBTHEATER_ID VARCHAR(18),
    SUBTHEATER_NAME VARCHAR(765),
    THEATER_ID VARCHAR(18),
    THEATER_NAME VARCHAR(765),
    GEOGRAPHIC_AREA_OWNER_ID VARCHAR(18),
    GEOGRAPHIC_AREA_OWNER_NAME VARCHAR(363),
    STATUS_CODE VARCHAR(3900),
    SOURCE_START_DATE DATE,
    SOURCE_END_DATE DATE,
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- DIMENSION: SALES USERS
-- ============================================================
CREATE OR REPLACE TABLE DIM_SALES_USER (
    DIM_SALES_USER_KEY VARCHAR(32),
    USER_ID VARCHAR(18) PRIMARY KEY,
    FIRST_NAME VARCHAR(120),
    LAST_NAME VARCHAR(240),
    FULL_NAME VARCHAR(363),
    EMAIL_ADDRESS_TEXT VARCHAR(384),
    TITLE_NAME VARCHAR(240),
    DEPARTMENT_NAME VARCHAR(240),
    ROLE_NAME VARCHAR(240),
    ROLE_ROLLUP_DESC VARCHAR(240),
    TEAM_ROLE_NAME VARCHAR(765),
    THEATER_NAME VARCHAR(60),
    CITY_NAME VARCHAR(120),
    STATE_PROVINCE_NAME VARCHAR(240),
    COUNTRY_NAME VARCHAR(240),
    ACTIVE_IND BOOLEAN DEFAULT TRUE,
    MANAGER_ID VARCHAR(18),
    COST_CENTER_CODE VARCHAR(90),
    WORKER_ID VARCHAR(60),
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- DIMENSION: WORKERS (Employee data from Workday)
-- ============================================================
CREATE OR REPLACE TABLE DIM_WORKER (
    DIM_WORKER_KEY VARCHAR(32),
    EMPLOYEE_ID VARCHAR(60) PRIMARY KEY,
    WORKER_TYPE_CODE VARCHAR(50),
    EMPLOYEE_TYPE_CODE VARCHAR(50),
    WORKER_HIRE_DATE DATE,
    WORKER_TERMINATION_DATE DATE,
    LEGAL_FIRST_NAME VARCHAR(120),
    LEGAL_LAST_NAME VARCHAR(240),
    LEGAL_FULL_NAME VARCHAR(363),
    PREFERRED_FIRST_NAME VARCHAR(120),
    PREFERRED_LAST_NAME VARCHAR(240),
    PREFERRED_FULL_NAME VARCHAR(363),
    BUSINESS_TITLE_NAME VARCHAR(240),
    JOB_FAMILY_NAME VARCHAR(240),
    JOB_PROFILE_TEXT VARCHAR(765),
    JOB_LEVEL_CODE VARCHAR(50),
    MANAGER_IND BOOLEAN,
    MANAGER_EMPLOYEE_ID VARCHAR(60),
    MANAGER_FIRST_NAME VARCHAR(120),
    MANAGER_LAST_NAME VARCHAR(240),
    F5_EMAIL_ADDRESS_TEXT VARCHAR(384),
    COST_CENTER_ID VARCHAR(60),
    COST_CENTER_NAME VARCHAR(240),
    FUNCTIONAL_AREA_NAME VARCHAR(240),
    LOCATION_NAME VARCHAR(240),
    LOCATION_CITY_NAME VARCHAR(120),
    LOCATION_COUNTRY_NAME VARCHAR(240),
    ACTIVE_STATUS_IND BOOLEAN DEFAULT TRUE,
    COMPANY_NAME VARCHAR(240),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- SALES ACCOUNT TEAM (Custom table for HOL)
-- ============================================================
CREATE OR REPLACE TABLE SALES_ACCOUNT_TEAM (
    SFDCF5_ACCT_ID VARCHAR(18),
    ACCT_NAME VARCHAR(765),
    AE_USER_ID VARCHAR(18),
    AE_NAME VARCHAR(363),
    AE_EMAIL VARCHAR(384),
    SE_USER_ID VARCHAR(18),
    SE_NAME VARCHAR(363),
    SE_EMAIL VARCHAR(384),
    SDR_USER_ID VARCHAR(18),
    SDR_NAME VARCHAR(363),
    SDR_EMAIL VARCHAR(384),
    CSM_USER_ID VARCHAR(18),
    CSM_NAME VARCHAR(363),
    CSM_EMAIL VARCHAR(384),
    TERRITORY_NAME VARCHAR(240),
    DISTRICT_NAME VARCHAR(90),
    REGION_NAME VARCHAR(765),
    THEATER_NAME VARCHAR(765),
    TIMEZONE_REGION VARCHAR(50),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- DIMENSION: PRODUCT CATALOG
-- ============================================================
CREATE OR REPLACE TABLE DIM_PRODUCT_OFFER (
    DIM_PRODUCT_OFFER_KEY VARCHAR(32),
    PRODUCT_ID VARCHAR(18) PRIMARY KEY,
    OFFER_SKU_ID VARCHAR(765),
    OFFER_DESC VARCHAR(4000),
    BRAND_NAME VARCHAR(90),
    CORE_PRODUCT_NAME VARCHAR(100),
    F5_PRODUCT_OFFER_FAMILY_NAME VARCHAR(90),
    PRODUCT_OFFERING_NAME VARCHAR(100),
    PRODUCT_OFFERING_TYPE_NAME VARCHAR(100),
    PRODUCT_OFFERING_SUB_TYPE_NAME VARCHAR(100),
    HARDWARE_PLATFORM_CODE VARCHAR(100),
    OFFER_STATUS_CODE VARCHAR(100),
    STANDARD_LIST_PRICE_AMT NUMBER(12,2),
    FORECAST_GROUP_NAME VARCHAR(765),
    BUSINESS_UNIT_NAME VARCHAR(3900),
    PRODUCT_LINE_TYPE VARCHAR(150),
    END_OF_SALE_DATE TIMESTAMP_NTZ(9),
    END_OF_HARDWARE_TECH_SUPPORT_DATE TIMESTAMP_NTZ(9),
    END_OF_SOFTWARE_TECH_SUPPORT_DATE DATE,
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- DIMENSION: SUBSCRIPTIONS
-- ============================================================
CREATE OR REPLACE TABLE DIM_PRODUCT_OFFER_SUBSCRIPTION (
    DIM_PRODUCT_OFFER_SUBSCRIPTION_KEY VARCHAR(32),
    SUBSCRIPTION_ID VARCHAR(960) PRIMARY KEY,
    SUBSCRIPTION_NUM VARCHAR(960),
    SFDCF5_ACCT_ID VARCHAR(18),
    PRODUCT_ID VARCHAR(18),
    SUBSCRIPTION_STATUS_CODE VARCHAR(256),
    SUBSCRIPTION_START_DATE TIMESTAMP_NTZ(9),
    SUBSCRIPTION_END_DATE TIMESTAMP_NTZ(9),
    CURRENT_TERM_MTH_NUM NUMBER(38,0),
    SUBSCRIPTION_VERSION_NUM NUMBER(38,0),
    PREVIOUS_SUBSCRIPTION_NUM VARCHAR(256),
    ORIGINAL_SUBSCRIPTION_NUM VARCHAR(256),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- DIMENSION: SALES OPPORTUNITIES
-- ============================================================
CREATE OR REPLACE TABLE DIM_SALES_OPPORTUNITY (
    DIM_SALES_OPPORTUNITY_KEY VARCHAR(32),
    OPPORTUNITY_ID VARCHAR(18) PRIMARY KEY,
    OPPORTUNITY_NAME VARCHAR(360),
    OPPORTUNITY_TYPE_CODE VARCHAR(765),
    OPPORTUNITY_STAGE_NAME VARCHAR(765),
    OPPORTUNITY_CLOSE_DATE DATE,
    OPPORTUNITY_CLOSE_PROBABILITY_PCT FLOAT,
    OPPORTUNITY_CREATED_DATE TIMESTAMP_TZ(9),
    OPPORTUNITY_OWNER_NAME VARCHAR(363),
    OPPORTUNITY_OWNER_ID VARCHAR(18),
    SFDCF5_ACCT_ID VARCHAR(18),
    FORECAST_CATEGORY_NAME VARCHAR(765),
    BUSINESS_TYPE_CODE VARCHAR(3900),
    DEAL_TYPE_CODE VARCHAR(765),
    COMPETITOR_NAME VARCHAR(300),
    PRIMARY_COMPETITOR_NAME VARCHAR(765),
    PRIMARY_REASON_WON_LOST_ABANDONED_CODE VARCHAR(765),
    REASON_WON_LOST_ABANDONED_DESC VARCHAR(765),
    OPPORTUNITY_WON_IND BOOLEAN,
    OPPORTUNITY_CLOSED_IND BOOLEAN,
    RENEWAL_FLAG VARCHAR(1),
    THEATER_NAME VARCHAR(765),
    TERRITORY_CREDITED_REGION_NAME VARCHAR(3900),
    TERRITORY_CREDITED_DISTRICT_NAME VARCHAR(3900),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- FACT: SALES OPPORTUNITIES (Dollar amounts)
-- ============================================================
CREATE OR REPLACE TABLE FACT_SALES_OPPORTUNITY (
    FACT_SALES_OPPORTUNITY_KEY VARCHAR(32),
    OPPORTUNITY_ID VARCHAR(18),
    SFDCF5_ACCT_ID VARCHAR(18),
    OPPORTUNITY_OWNER_ID VARCHAR(18),
    PRIMARY_F5_SYSTEM_ENGINEER_ID VARCHAR(18),
    OPPORTUNITY_CLOSE_DATE DATE,
    OPPORTUNITY_CREATED_DATE TIMESTAMP_NTZ(9),
    OPPORTUNITY_AMT NUMBER(35,17),
    PI_AMT NUMBER(35,17),
    ARR_AMT NUMBER(35,17),
    FYB_AMT NUMBER(35,17),
    MRR_ROLLUP_AMT NUMBER(35,17),
    TOTAL_CONTRACT_BOOKING_AMT NUMBER(35,17),
    SUBSCRIPTION_BOOKING_AMT NUMBER(35,17),
    SECURITY_PI_AMT NUMBER(35,17),
    UPSELL_ACV_AMT NUMBER(35,17),
    VARICENT_TERRITORY_CODE VARCHAR(765),
    TERM_DURATION_MONTHS_NUM NUMBER(38,10),
    TERM_START_DATE DATE,
    TERM_END_DATE DATE,
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- FACT: OPPORTUNITY LINE ITEMS
-- ============================================================
CREATE OR REPLACE TABLE FACT_SALES_OPPORTUNITY_LINE_ITEM (
    FACT_SALES_OPPORTUNITY_LINE_ITEM_KEY VARCHAR(32),
    LINE_ITEM_ID VARCHAR(18) PRIMARY KEY,
    OPPORTUNITY_ID VARCHAR(18),
    SFDCF5_ACCT_ID VARCHAR(18),
    PRODUCT_ID VARCHAR(18),
    PRODUCT_SKU_ID VARCHAR(180),
    BRAND_NAME VARCHAR(105),
    F5_PRODUCT_FAMILY_NAME VARCHAR(150),
    LINE_ITEM_NAME VARCHAR(1128),
    PRODUCT_QTY FLOAT,
    TOTAL_PRICE_AMT NUMBER(35,17),
    NET_PRICE_AMT NUMBER(35,17),
    ARR_AMT NUMBER(35,17),
    MRR_AMT NUMBER(35,17),
    CONTRACT_LENGTH_MTH_NUM FLOAT,
    LINE_ITEM_START_DATE DATE,
    LINE_ITEM_END_DATE DATE,
    OPPORTUNITY_CLOSE_DATE DATE,
    OPPORTUNITY_OWNER_ID VARCHAR(18),
    TERRITORY_CREDITED_ID VARCHAR(18),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- FACT: SALES PIPELINE SNAPSHOTS (weekly point-in-time)
-- ============================================================
CREATE OR REPLACE TABLE FACT_SALES_PIPELINE_SNAPSHOT (
    FACT_SALES_PIPELINE_SNAPSHOT_KEY VARCHAR(32),
    SNAPSHOT_DATE DATE,
    OPPORTUNITY_ID VARCHAR(18),
    LINE_ITEM_ID VARCHAR(18),
    ACCT_NAME VARCHAR(765),
    OPPORTUNITY_NAME VARCHAR(360),
    OPPORTUNITY_STAGE_NAME VARCHAR(765),
    OPPORTUNITY_CLOSE_DATE DATE,
    OPPORTUNITY_CLOSE_PROBABILITY_PCT FLOAT,
    OPPORTUNITY_OWNER_NAME VARCHAR(363),
    FORECAST_CATEGORY_NAME VARCHAR(765),
    PI_TOTAL_PRICE_AMT NUMBER(18,2),
    PRODUCT_SKU_ID VARCHAR(180),
    BRAND_NAME VARCHAR(90),
    CORE_PRODUCT_NAME VARCHAR(300),
    INDUSTRY_NAME VARCHAR(765),
    TERRITORY_NAME VARCHAR(240),
    TERRITORY_REGION_NAME VARCHAR(765),
    TERRITORY_THEATER_NAME VARCHAR(3900),
    WEEKLY_SNAPSHOT_FLAG VARCHAR(1) DEFAULT 'Y',
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- QUOTES
-- ============================================================
CREATE OR REPLACE TABLE QUOTE (
    ID VARCHAR(32) PRIMARY KEY,
    SOURCE_ID VARCHAR(18),
    OPPORTUNITY_ID VARCHAR(18),
    SFDCF5_ACCT_ID VARCHAR(18),
    QUOTE_APPROVED_DATE DATE,
    AMOUNT NUMBER(35,17),
    IS_PRIMARY_FLAG VARCHAR(1),
    STATUS_CODE VARCHAR(100),
    START_DATETIME TIMESTAMP_NTZ(9),
    END_DATETIME TIMESTAMP_NTZ(9),
    ACTIVE_FLAG VARCHAR(1) DEFAULT 'Y',
    DELETED_FLAG BOOLEAN DEFAULT FALSE,
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- CONTRACTS / ELA HEADERS
-- ============================================================
CREATE OR REPLACE TABLE USER_ENTRY_HEADER (
    LEGAL_CONTRACT_ID VARCHAR(1020) PRIMARY KEY,
    SFDCF5_ACCT_ID VARCHAR(18),
    LEGAL_CONTRACT_START_DATE DATE,
    LEGAL_CONTRACT_END_DATE DATE,
    TRUE_FORWARD_METHOD_NAME VARCHAR(10),
    TOTAL_DISCOUNT_OFF_LIST_PCT NUMBER(38,3),
    NGINX_COMMIT_AMT NUMBER(38,3),
    BIG_IP_VE_COMMIT_AMT NUMBER(38,3),
    LOGIN_NAME VARCHAR(200),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- DIMENSION: SUPPORT CASES
-- ============================================================
CREATE OR REPLACE TABLE DIM_SUPPORT_CASE (
    DIM_SUPPORT_CASE_KEY VARCHAR(32),
    SUPPORT_CASE_ID VARCHAR(18) PRIMARY KEY,
    SUPPORT_CASE_NUM VARCHAR(100),
    PARENT_SUPPORT_CASE_ID VARCHAR(18),
    SFDCF5_ACCT_ID VARCHAR(18),
    SUPPORT_CASE_TITLE_TEXT VARCHAR(765),
    SUPPORT_CASE_STATUS_CODE VARCHAR(765),
    SUPPORT_CASE_SUB_STATUS_CODE VARCHAR(765),
    CURRENT_PRIORITY_CODE VARCHAR(765),
    INITIAL_PRIORITY_CODE VARCHAR(765),
    HIGHEST_PRIORITY_CODE VARCHAR(765),
    SUPPORT_CASE_TYPE_CODE VARCHAR(80),
    SUPPORT_CASE_SUBTYPE_CODE VARCHAR(765),
    PRODUCT_NAME VARCHAR(765),
    PRODUCT_SKU_ID VARCHAR(765),
    AREA_NAME VARCHAR(80),
    SUB_AREA_NAME VARCHAR(80),
    SERIAL_NUM VARCHAR(16777216),
    CREATED_DATETIME TIMESTAMP_NTZ(9),
    OPENED_DATETIME TIMESTAMP_NTZ(9),
    RESOLVED_DATETIME TIMESTAMP_NTZ(9),
    CLOSED_DATETIME TIMESTAMP_NTZ(9),
    FIRST_RESPONSE_DATETIME TIMESTAMP_NTZ(9),
    SLM_DUE_DATETIME TIMESTAMP_NTZ(9),
    CONTACT_FULL_NAME VARCHAR(361),
    CONTACT_EMAIL_ADDRESS_TEXT VARCHAR(240),
    CONTACT_PHONE_NUM VARCHAR(120),
    SERVICE_LEVEL_CODE VARCHAR(765),
    ENTITLEMENT_TYPE_CODE VARCHAR(765),
    RESOLUTION_CODE VARCHAR(80),
    SUPPORT_CASE_RECORD_TYPE VARCHAR(3900),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- FACT: SUPPORT CASES (Metrics - time to close/response/SLA)
-- ============================================================
CREATE OR REPLACE TABLE FACT_SUPPORT_CASE (
    SUPPORT_CASE_ID VARCHAR(18) PRIMARY KEY,
    PARENT_SUPPORT_CASE_ID VARCHAR(18),
    SERIAL_NUM VARCHAR(16777216),
    CUST_SFDCF5_ACCT_ID VARCHAR(18),
    SALES_SFDCF5_ACCT_ID VARCHAR(18),
    DIM_SUPPORT_CASE_KEY VARCHAR(32),
    DIM_CUST_ACCT_SFDC_KEY VARCHAR(32),
    TIME_TO_CLOSE_MINUTES_NUM NUMBER(18,0),
    TIME_TO_RESPONSE_MINUTES_NUM NUMBER(38,0),
    TIME_OVER_UNDER_SLA_MINUTES_NUM NUMBER(18,0),
    TIME_TO_RESOLUTION_MINUTES_NUM NUMBER(18,0),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- COLLECTION: SUPPORT CASES (Enriched view with territory)
-- ============================================================
CREATE OR REPLACE TABLE COL_SUPPORT_CASE (
    SALES_SFDCF5_ACCT_ID VARCHAR(18),
    TERRITORY_OWNER_NAME VARCHAR(363),
    TERRITORY_NAME VARCHAR(240),
    DISTRICT_NAME VARCHAR(90),
    REGION_NAME VARCHAR(765),
    THEATER_NAME VARCHAR(765),
    SERIAL_NUM VARCHAR(16777216),
    SUPPORT_CASE_NUM VARCHAR(100),
    SERVICE_REQUEST_NUMBER VARCHAR(100),
    SUPPORT_CASE_TITLE_TEXT VARCHAR(765),
    STATUS VARCHAR(765),
    SEVERITY_CODE VARCHAR(765),
    PRODUCT_SKU_ID VARCHAR(765),
    OPEN_DATE TIMESTAMP_NTZ(9),
    CLOSE_DATE TIMESTAMP_NTZ(9),
    SUPPORT_CASE_OPEN_DAYS NUMBER(9,0),
    CONTACT_FULL_NAME VARCHAR(361),
    CONTACT_EMAIL_ADDRESS_TEXT VARCHAR(240),
    CONTACT_PHONE_NUM VARCHAR(120),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- FACT: RMA ORDERS (Return Merchandise Authorization)
-- ============================================================
CREATE OR REPLACE TABLE FACT_RMA_ORDER (
    ORDER_NUM VARCHAR(25) PRIMARY KEY,
    SFDCF5_ACCT_ID VARCHAR(18),
    DIM_SUPPORT_CASE_KEY VARCHAR(32),
    DIM_CUST_ACCT_SFDC_KEY VARCHAR(32),
    ORDER_DATETIME TIMESTAMP_NTZ(9),
    RMA_SYSTEM_PART_NUM VARCHAR(255),
    RMA_APPLIANCE_PART_NUM VARCHAR(255),
    RMA_SYSTEM_SERIAL_NUM VARCHAR(30),
    RMA_APPLIANCE_SERIAL_NUM VARCHAR(30),
    SHIPPED_QTY FLOAT,
    STATUS_CODE VARCHAR(50),
    SHIP_DATE DATE,
    SUPPORT_CASE_NUM VARCHAR(100),
    SYMPTOM_CLASS_CODE VARCHAR(50),
    SYMPTOM_DESC VARCHAR(4000),
    RMA_DOA_FLAG VARCHAR(1),
    APPROVED_FLAG VARCHAR(1),
    CANCELLED_FLAG VARCHAR(1),
    CLOSED_FLAG VARCHAR(1),
    SHIP_TO_CITY_NAME VARCHAR(120),
    SHIP_TO_COUNTRY_NAME VARCHAR(255),
    SHIP_TO_STATE_ABV VARCHAR(120),
    REPLACEMENT_SERIAL_NUM VARCHAR(30),
    CREATED_DATETIME TIMESTAMP_NTZ(9),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- COLLECTION: INSTALL BASE (What's deployed at customer sites)
-- ============================================================
CREATE OR REPLACE TABLE COL_INSTALL_BASE (
    OFFER_SKU_ID VARCHAR(769),
    OFFER_DESC VARCHAR(4000),
    CUST_SFDCF5_ACCT_ID VARCHAR(18),
    SALES_SFDCF5_ACCT_ID VARCHAR(256),
    ACCOUNT_NAME VARCHAR(765),
    CORE_PRODUCT_NAME VARCHAR(100),
    HARDWARE_PLATFORM_CODE VARCHAR(100),
    PLATFORM VARCHAR(16777216),
    SERIAL_NUM VARCHAR(16777216),
    PARENT_SERIAL_NUM VARCHAR(30),
    SHIP_DATE TIMESTAMP_NTZ(9),
    SOFTWARE_VERSION_NUM VARCHAR(16777216),
    SERVICE_END_DATETIME TIMESTAMP_NTZ(9),
    END_OF_SOFTWARE_DEVELOPMENT_DATE DATE,
    EOTS_DATE DATE,
    SUBSCRIPTION_NUM VARCHAR(16777216),
    RESELLER VARCHAR(1440),
    ACCOUNT_OWNER VARCHAR(363),
    ETM_TERRITORY_NAME VARCHAR(300),
    ETM_DISTRICT_NAME VARCHAR(300),
    ETM_REGION_NAME VARCHAR(300),
    ETM_THEATER_NAME VARCHAR(300),
    BILLING_COUNTRY_NAME VARCHAR(240),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- COLLECTION: CUSTOMER CENTRAL (Full product/service view)
-- ============================================================
CREATE OR REPLACE TABLE COL_CORP_CUSTOMER_CENTRAL_PRODUCT_OFFER_CUST_VALUE (
    DIM_CUST_PROF_EBS_SITE_KEY VARCHAR(32),
    CUST_SFDCF5_ACCT_ID VARCHAR(18),
    SALES_SFDCF5_ACCT_ID VARCHAR(256),
    OFFER_SKU_ID VARCHAR(769),
    OFFER_DESC VARCHAR(4000),
    CORE_PRODUCT_NAME VARCHAR(100),
    HARDWARE_PLATFORM_CODE VARCHAR(100),
    SERIAL_NUM VARCHAR(16777216),
    SHIP_DATE DATE,
    SUBSCRIPTION_NUM VARCHAR(16777216),
    SUBSCRIPTION_START_DATE TIMESTAMP_NTZ(9),
    SUBSCRIPTION_END_DATE TIMESTAMP_NTZ(9),
    SERVICE_END_DATETIME TIMESTAMP_NTZ(9),
    END_OF_SALE_DATE TIMESTAMP_NTZ(9),
    END_OF_SOFTWARE_TECH_SUPPORT_DATE DATE,
    END_OF_HARDWARE_TECH_SUPPORT_DATE TIMESTAMP_NTZ(9),
    SOFTWARE_VERSION_NUM VARCHAR(16777216),
    PRODUCT_OFFERING_SUB_TYPE_NAME VARCHAR(100),
    PARTY_NAME VARCHAR(1440),
    CITY_NAME VARCHAR(400),
    STATE_NAME VARCHAR(400),
    COUNTRY_NAME VARCHAR(400),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- TELEMETRY: XC/Distributed Cloud Usage
-- ============================================================
CREATE OR REPLACE TABLE COL_XC_TELEMETRY (
    COL_XC_TELEMETRY_KEY VARCHAR(32),
    TENANT_ID VARCHAR(256),
    SFDCF5_ACCT_ID VARCHAR(18),
    ACCT_NAME VARCHAR(765),
    OBSERVATION_DATE DATE,
    CURRENT_OBSERVATION_FLAG VARCHAR(1),
    ACTIVE_HTTP_LOAD_BALANCER_QTY NUMBER(38,0),
    ACTIVE_TCP_LOAD_BALANCER_QTY NUMBER(38,0),
    ACTIVE_ENDPOINT_QTY NUMBER(38,0),
    WAF_USAGE_QTY NUMBER(38,0),
    BOT_DEFENSE_IND BOOLEAN,
    BOT_ADVANCED_TRANSACTION_CNT NUMBER(38,0),
    BOT_STANDARD_TRANSACTION_CNT NUMBER(38,0),
    API_DISCOVERY_LOAD_BALANCER_QTY NUMBER(38,6),
    API_PROTECTION_GOOD_REQUESTS_MILLIONS_QTY NUMBER(38,6),
    DNS_ZONES_QTY NUMBER(38,0),
    DNS_LOAD_BALANCER_QTY NUMBER(38,0),
    NAMESPACE_QTY NUMBER(38,0),
    SITE_QTY NUMBER(38,0),
    USER_QTY NUMBER(38,0),
    VIRTUAL_HOSTS_QTY NUMBER(38,0),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- TELEMETRY: Account-to-Tenant Mapping
-- ============================================================
CREATE OR REPLACE TABLE COL_XC_TELEMETRY_ACCT_MAP_V2 (
    SFDCF5_ACCT_ID VARCHAR(18),
    TENANT_ID VARCHAR(256),
    SUBSCRIPTION_NUM VARCHAR(256),
    ENTITLEMENT_ID VARCHAR(256),
    ORDER_TYPE_NAME VARCHAR(64),
    TELEMETRY_RECEIVED_FLAG VARCHAR(1),
    TELEMETRY_RECEIVED_AT_ACCT_LEVEL_STATUS VARCHAR(7),
    TERRITORY_CODE VARCHAR(60),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- TELEMETRY: Monthly Subscription Usage (Consumption)
-- ============================================================
CREATE OR REPLACE TABLE COL_TERM_SUB_MONTHLY_USAGE_V2 (
    TENANT_ID VARCHAR(256),
    BILLING_MONTH_START_DATE DATE,
    BILLING_MONTH_NAME VARCHAR(9),
    BILLING_YEAR_NUM NUMBER(38,0),
    CUST_ACCT_ID VARCHAR(18),
    ACCT_NAME VARCHAR(500),
    SALES_SFDCF5_ACCT_ID VARCHAR(64),
    SUBSCRIPTION_NUM VARCHAR(64),
    SUBSCRIPTION_START_DATE DATE,
    SUBSCRIPTION_END_DATE DATE,
    SUBSCRIPTION_STATUS_CODE VARCHAR(756),
    PRODUCT_NAME VARCHAR(256),
    OFFER_SKU_ID VARCHAR(100),
    OFFER_DESC VARCHAR(1500),
    FEATURE_NAME VARCHAR(765),
    FEATURE_ENTITLED_QTY NUMBER(38,6),
    FEATURE_USED_QTY NUMBER(38,6),
    SKU_ENTITLED_QTY NUMBER(38,0),
    SKU_USED_QTY NUMBER(38,0),
    DERIVED_UOM VARCHAR(100),
    MONTHS_IN_TERM_NUM NUMBER(9,0),
    MONTHS_LEFT_IN_TERM_NUM NUMBER(9,0),
    TELEMETRY_RECEIVED_FLAG VARCHAR(1),
    ERROR_MESSAGE_LIST VARCHAR(600),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- TELEMETRY: Product Health Scores
-- ============================================================
CREATE OR REPLACE TABLE COL_XC_PRODUCT_HEALTHSCORE (
    COL_XC_PRODUCT_HEALTHSCORE_KEY VARCHAR(32),
    SFDCF5_ACCT_ID VARCHAR(18),
    ACCT_NAME VARCHAR(765),
    ACCT_OWNER_NAME VARCHAR(600),
    SUBSCRIPTION_NUM VARCHAR(600),
    SUBSCRIPTION_STATUS_CODE VARCHAR(200),
    SUBSCRIPTION_START_DATE DATE,
    SUBSCRIPTION_END_DATE DATE,
    BILLING_MONTH_START_DATE DATE,
    OFFER_SKU_ID VARCHAR(600),
    SKU_UTILIZATION_PCT NUMBER(38,2),
    SKU_USED_QTY NUMBER(38,2),
    SKU_ENTITLED_QTY NUMBER(38,2),
    CONSUMPTION_PATTERN VARCHAR(23),
    PRODUCT_LINE VARCHAR(38),
    CORE_PRODUCT VARCHAR(38),
    BUSINESS_LINE VARCHAR(38),
    TELEMETRY_RECEIVED_FLAG VARCHAR(1),
    CURRENT_BILLING_MONTH_FLAG VARCHAR(1),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- TELEMETRY: Bot Defense (Raw telemetry)
-- ============================================================
CREATE OR REPLACE TABLE BASE_XC_TELEMETRY_NON_COMMERCIAL_BOT_STANDARD (
    TENANT VARCHAR(256),
    DATE DATE,
    PRODUCT VARCHAR(256),
    TRANSACTION_TYPE VARCHAR(256),
    CLIENT_TYPE VARCHAR(256),
    ACTION_TYPE VARCHAR(256),
    TRAFFIC_TYPE VARCHAR(256),
    VALUE NUMBER(38,0),
    ENTITLEMENT_ID VARCHAR(256),
    UNIT_OF_MEASURE VARCHAR(256),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- DIMENSION: DATE (Fiscal calendar)
-- ============================================================
CREATE OR REPLACE TABLE DIM_DAY_DATE (
    DIM_DAY_DATE_KEY NUMBER(38,0) PRIMARY KEY,
    CALENDAR_DATE DATE,
    CAL_DAY_IN_WEEK VARCHAR(7),
    CAL_DAY_IN_WEEK_NUM NUMBER(38,0),
    CAL_DAY_IN_MTH_NUM NUMBER(38,0),
    CAL_WEEK_IN_YEAR_NUM NUMBER(38,0),
    CAL_MTH_NUM NUMBER(38,0),
    CAL_MTH_NAME VARCHAR(16777216),
    CAL_QTR_NUM NUMBER(38,0),
    CAL_YEAR_NUM NUMBER(38,0),
    FISCAL_YEAR_NUM NUMBER(38,0),
    FISCAL_MTH_NAME VARCHAR(9),
    FISCAL_QTR_CODE VARCHAR(7),
    FISCAL_QTR_WEEK_NUM NUMBER(38,0),
    CURRENT_FISCAL_MTH_FLAG VARCHAR(7),
    CURRENT_FISCAL_QTR_FLAG VARCHAR(7),
    CURRENT_FISCAL_YEAR_FLAG VARCHAR(7),
    CURRENT_FISCAL_WEEK_FLAG VARCHAR(7),
    FIRST_DAY_IN_QTR_DATE DATE,
    LAST_DAY_IN_QTR_DATE DATE,
    FISCAL_PERIOD_DESC VARCHAR(16777216),
    WEEK_DAY_FLAG VARCHAR(7),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- TERRITORY SECURITY (Row-level access control for territories)
-- ============================================================
CREATE OR REPLACE TABLE SALES_SECURITY_ETM_TERRITORY (
    ETM_TERRITORY_ID VARCHAR(18),
    ETM_TERRITORY_NAME VARCHAR(240),
    VARICENT_TERRITORY_CODE VARCHAR(765),
    PERMITTED_USER_EMAIL_ADDRESS_TEXT VARCHAR(16777216),
    PERMITTED_USER_ROLE VARCHAR(24),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- COLLECTION: OPPORTUNITY LINE ITEMS (Enriched flat view)
-- ============================================================
CREATE OR REPLACE TABLE COL_SALES_OPPORTUNITY_LINE_ITEM (
    COL_SALES_OPPORTUNITY_LINE_ITEM_KEY VARCHAR(1202),
    SFDCF5_ACCT_ID VARCHAR(18),
    ACCT_NAME VARCHAR(765),
    OPPORTUNITY_ID VARCHAR(18),
    OPPORTUNITY_NAME VARCHAR(360),
    OPPORTUNITY_CREATED_DATE TIMESTAMP_NTZ(9),
    OPPORTUNITY_CLOSE_DATE DATE,
    OPPORTUNITY_CLOSE_PROBABILITY_PCT FLOAT,
    LINE_ITEM_ID VARCHAR(18),
    PRODUCT_SKU_ID VARCHAR(180),
    PRODUCT_QTY FLOAT,
    TOTAL_PRICE_AMT FLOAT,
    THEATER_NAME VARCHAR(765),
    BILLING_COUNTRY_NAME VARCHAR(240),
    INDUSTRY_GROUPING_CODE VARCHAR(765),
    VARICENT_TERRITORY_CODE VARCHAR(765),
    ACCT_REGION_NAME VARCHAR(765),
    ACCT_DISTRICT_NAME VARCHAR(90),
    ACCT_TERRITORY_NAME VARCHAR(240),
    FORECAST_FISCAL_WEEK_NUM VARCHAR(16777216),
    MONTHLY_FORECAST_CATEGORY_CODE VARCHAR(3900),
    EDE_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EDE_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- ZOOM TRANSCRIPT STAGE
-- ============================================================
CREATE OR REPLACE STAGE ZOOM_TRANSCRIPTS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for Zoom call transcript files in WEBVTT format';
